version: "2"

setup:
  go: "1.25"

linters:
  default:
    enabled: true
  disable:
    - funlen
    - gomnd
    - exhaustruct
    - wsl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    json:
      path: "/tmp/results.json"