linters-settings:
  gocyclo:
    min-complexity: 24
  cyclop:
    max-complexity: 24
  forbidigo:
    forbid:
      - .*\.fatal,*
      - fmt.Print.*
  gci:
    skip-generated: true
  gofmt:
    simplify: true

linters:
  enable-all: true

  disable:
    - funlen
    - depguard
    - execinquery
    - exportloopref
    - exhaustruct
    - gomnd
    - ireturn
    - tagalign
    - varnamelen
    - wastedassign

run:
  timeout: 5m
  tests: false

output:
  formats:
  - format: colored-line-number
