version: "2"

linters-settings:
  gocyclo:
    min-complexity: 24
  cyclop:
    max-complexity: 24
  forbidigo:
    forbid:
      - '^fmt\.Print.*$'
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/your-username)
    skip-generated: true
  lll:
    line-length: 160

linters:
  enable-all: true
  disable:
    - funlen
    - depguard
    - execinquery
    - exportloopref
    - exhaustruct
    - gomnd
    - ireturn
    - tagalign
    - varnamelen
    - wastedassign

run:
  timeout: 5m
  tests: false

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true