linters-settings:
  gocyclo:
    min-complexity: 24
  cyclop:
    max-complexity: 24
  forbidigo:
    forbid:
      - .*\.fatal,*
      - fmt.Print.*
  gci:
    skip-generated: true

linters:
  enable-all: true

  disable:
    - gci
    - gofmt
    - funlen
    - depguard
    - exhaustive
    - exhaustruct
    - gomnd
    - ireturn
    - varnamelen
    - tagalign
    - wastedassign
    - execinquery
    - revive
    - godox
    - unused
    - err113

run:
  timeout: 5m

output:
  formats:
  - format: colored-line-number