version: "2"


linters:
  default: standard
  disable:
    - funlen
    - exhaustruct
    - wsl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    json:
      path: "/tmp/results.json"